name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["alerwann-fortquest"] # Vérifie que c'est bien le nom de ta branche principale

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Angular 19 préfère une version récente

      - name: Install dependencies
        run: npm ci

      - name: Build
        # Remplace 'alerwann-fortquest' par le nom exact de ton projet dans angular.json si besoin
        run: npx ng build --base-href /alerwann-fortquest/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # C'est ici que tu pointes vers le dossier généré par Angular
          path: './dist/alerwann-fortquest/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4